### ISSUE TITLE
WHich file is the first playbook to run

### ISSUE THREAD

**Issue by EtaiNatanel** [MVladislav/ansible-cis-ubuntu-2204#1]
### Describe the problem

I got a problem, I don't know which playbook to run first, and when I try to run some of the playbooks I get an error on all of them which I tried.
I know I have all the requirements because I ran the prepare.yml and it ran, but the other .yml files didn't run.

### Expected behavior

I can't understand which one is the first and if I need to change something

### What is version of application which has the issue?

Ubuntu2204

### What type of installation are you running?

OS (setup.py)

### What type of device you use to interact with the application?

OS: [e.g. linux, windows, ios]

**Comment by MVladislav** [comment]
Hi,

what do you mean with which playbook first to run?

This one is a complete role, if you want a quick start for that role, 
you can try the short docu/post i created: https://mvladislav.online/posts/ansible-cis-ubuntu-2204/

**Comment by Gokul-C** [comment]
Hi, @EtaiNatanel I think I understand your problem.

First, you need to install the ansible role for that run the below command:
`ansible-galaxy install role git+https://github.com/MVladislav/ansible-cis-ubuntu-2204.git`

**You can list installed roles** 
`ansible-galaxy role list`

<img width="298" alt="image" src="https://github.com/MVladislav/ansible-cis-ubuntu-2204/assets/46756853/13e9520e-62c6-4d99-be0b-c173723a9b62">


**Now you simply run this role using ansible-playbook**
```
---
- name: Ubuntu2204 CIS Hardening
  hosts: localhost
  become: true
  roles:
    - role: "ansible-cis-ubuntu-2204"
```
**To run this playbook**
`ansible-playbook --become-password-file /tmp/pass.txt /tmp/CIS-Hardening.yaml -vvvv`

In the /tmp/pass.txt file I just mentioned my root user password, so that I can skip manual typing.
